name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  coding_standards:
    name: Coding Standards
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.2, 8.3, 8.4]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run code quality
        run: composer code-quality
