name: Continuous Integration
on:
  push:
    branches:
      - master
      - '[0-9]+\-[0-9]+\-x'
  pull_request:

jobs:
  coding_standards:
    name: Coding Standards
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.1, 8.2, 8.3]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: php-cs-fixer
      - name: Check PHP CS
        run: php-cs-fixer fix --config .php-cs-fixer.php --dry-run --using-cache no --show-progress dots -v
